temp pr

diff --git a/.github/workflows/auto_cherry_pick.yml b/.github/workflows/auto_cherry_pick.yml
--- a/.github/workflows/auto_cherry_pick.yml
+++ b/.github/workflows/auto_cherry_pick.yml
@@ -200,6 +200,7 @@ jobs:
 
           SKIPPED_COMMITS=""
           CHANGES_FOUND=false
+          MISSING_FILES=""
 
           while read -r COMMIT_HASH; do
             echo "Processing commit: $COMMIT_HASH"
@@ -252,13 +253,14 @@ jobs:
                 SHA=$(echo "$FILE_RESPONSE" | jq -r .sha 2>/dev/null || echo "null")
 
                 if [ "$FILE_RESPONSE" == "ERROR" ] || [ -z "$SHA" ] || [ "$SHA" == "null" ]; then
-                  echo "⚠️ File $file does not exist in target repo. Creating it..."
-                  echo "" > temp_file.txt  # Create an empty file
-                else
-                  BASE64_CONTENT=$(echo "$FILE_RESPONSE" | jq -r '.content' | base64 --decode 2>/dev/null || echo "ERROR")
-                  if [ "$BASE64_CONTENT" != "ERROR" ]; then
-                    echo "$BASE64_CONTENT" > temp_file.txt
-                  fi
+                  echo "⚠️ File $file does not exist in target repo."
+                  MISSING_FILES="${MISSING_FILES}\n$file"
+                  continue
+                fi
+
+                BASE64_CONTENT=$(echo "$FILE_RESPONSE" | jq -r '.content' | base64 --decode 2>/dev/null || echo "ERROR")
+                if [ "$BASE64_CONTENT" != "ERROR" ]; then
+                  echo "$BASE64_CONTENT" > temp_file.txt
                 fi
 
                 PATCH=$(echo "$COMMIT_DETAILS" | jq -r '.files[] | select(.filename=="'$file'") | .patch' 2>/dev/null || echo "ERROR")
@@ -319,6 +321,9 @@ jobs:
           echo -e "$SKIPPED_COMMITS" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
+          echo "MISSING_FILES<<EOF" >> $GITHUB_ENV
+          echo -e "$MISSING_FILES" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
 
       - name: Set Up Node.js
         if: env.action_type == 'node'
@@ -478,6 +483,13 @@ jobs:
               done <<< "${{ env.SKIPPED_COMMITS }}"
               echo ""
             fi
+            if [ -n "${{ env.MISSING_FILES }}" ]; then
+              echo "❗ Missing Files:"
+              while IFS= read -r line; do
+                echo "- $line"
+              done <<< "${{ env.MISSING_FILES }}"
+              echo ""
+            fi
           } > "$COMMENT_BODY"
 
           EXISTING_COMMENT_ID=$(gh api "repos/$REPO/issues/$PR_NUMBER/comments" --jq '.[] | select(.body | contains("🚀 PR Updated!")) | .id')
@@ -485,7 +497,7 @@ jobs:
           if [ -n "$EXISTING_COMMENT_ID" ]; then
             echo "Updating existing comment: $EXISTING_COMMENT_ID"
             gh api --method PATCH "repos/$REPO/issues/comments/$EXISTING_COMMENT_ID" \
-              -F body="@$COMMENT_BODY"
+              -F body="$(cat "$COMMENT_BODY")"
           else
             echo "📝 Creating a new comment on PR #$PR_NUMBER"
             gh pr comment "$PR_NUMBER" --repo "$REPO" --body-file "$COMMENT_BODY"
